spring.application.name=vaelis-api

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/vaelis
spring.datasource.username=postgres
spring.datasource.password=Thakur@2007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
vaelis.frontend.url=http://localhost:3000